user01:
  name: lisi
  age: 20
tompet:
  pet-name: tom
  weight: 9.3
person:
  user-name: zhangsan
  boss: false
  birth: 2020/5/18 14:43:11
  age: 20
  pet:
    pet-name: tomcat
    weight: 3.6
  interests: [music,basketball,book,food]
  animal:
    - jerry
    - tom
    - bruto
    - bigyellow
  score: {1.2,5.6,4.3,100.1}
  salarys: [3333,22222,5555]
  all-pets:
    health: [{pet-name: tom,weight: 9.3},{pet-name: jerry,weight: 1.2}]
    sick:
      - {pet-name: bruto,weight: 15.3}
      - {pet-name: bigyellow,weight: 19}
#spring:
#  thymeleaf:
#    prefix: classpath:/templ/  # 访问temp下的html文件需要配置模板，映射
##            classpath: /templates   # 访问template下的html文件需要配置模板，映射
#    cache: false # 开发时关闭缓存,不然没法看到实时页面